version: '2'
volumes:
  aula2-logs:
services:
  aula2:
    image: oficina-docker:aula2-volumes
    build: .
    container_name: aula-2
    volumes:
     - aula2-logs:/tmp
  web:
    image: nginx
    ports:
     - "8080:80"
volumes:
  aula2-logs:
